require("modules.autostart")
require("modules.decorations")
require("modules.hyprland-gui")
require("modules.input")
require("modules.keybinds")
require("modules.layout")
require("modules.misc")
require("modules.monitors")
