add_newline = true

format = """
[╭─](white) [ ](bold blue)[$directory](bold cyan)[$git_branch](bold purple)
[╰─❯](white) """

[directory]
home_symbol = " ~"
truncation_length = 3
truncation_symbol = ".../"
read_only = "  "
read_only_style = "bold red"

[directory.substitutions]
"Desktop" = "󰍹 "
"Documents" = "󰈙"
"Downloads" = "󰇚"
"Music" = "󰎈"
"Pictures" = "󰋩 "
"Public" = "󰡅 "
"Videos" = "󰕧 "

[git_branch]
symbol = " "
